package native

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func RenderGo(proto *Proto, outDir string) (string, error) {
	if proto == nil {
		return "", fmt.Errorf("nil proto")
	}
	if outDir == "" {
		outDir = "."
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return "", err
	}
	path := filepath.Join(outDir, fmt.Sprintf("%s_bp.go", proto.Name))
	content, err := renderGoFile(proto)
	if err != nil {
		return "", err
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

func renderGoFile(proto *Proto) (string, error) {
	idx := newIndex(proto)
	pkg := strings.ToLower(proto.Name)
	var b strings.Builder

	b.WriteString("// Code generated by bitproto-go native renderer (experimental). DO NOT EDIT.\n\n")
	b.WriteString("package " + pkg + "\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\tbp \"github.com/tsingson/bitproto/lib/go\"\n")
	b.WriteString(")\n\n")
	b.WriteString("var jsonMarshal = json.Marshal\n")
	b.WriteString("var _ = bp.Useless\n\n")

	for _, c := range proto.Consts {
		b.WriteString(fmt.Sprintf("const %s %s = %s\n", c.Name, c.Type, c.Value))
	}
	if len(proto.Consts) > 0 {
		b.WriteString("\n")
	}

	for _, a := range proto.Aliases {
		ts, err := idx.goType(a.Type)
		if err != nil {
			return "", err
		}
		an := toPascal(a.Name)
		b.WriteString(fmt.Sprintf("type %s %s\n\n", an, ts))
		targetExpr, err := idx.goProcessorExpr(a.Type)
		if err != nil {
			return "", err
		}
		b.WriteString(fmt.Sprintf("func (m %s) BpProcessor() bp.Processor {\n", an))
		b.WriteString(fmt.Sprintf("\treturn bp.NewAliasProcessor(%s)\n", targetExpr))
		b.WriteString("}\n\n")
	}

	for _, e := range proto.Enums {
		base, err := idx.goScalarType(TypeExpr{Name: e.Base})
		if err != nil {
			return "", err
		}
		en := toPascal(e.Name)
		b.WriteString(fmt.Sprintf("type %s %s\n\n", en, base))
		b.WriteString("const (\n")
		for i, f := range e.Fields {
			if i == 0 {
				b.WriteString(fmt.Sprintf("\t%s %s = %d\n", f.Name, en, f.Value))
			} else {
				b.WriteString(fmt.Sprintf("\t%s = %d\n", f.Name, f.Value))
			}
		}
		b.WriteString(")\n\n")
		nbits, err := idx.scalarBits(e.Base)
		if err != nil {
			return "", err
		}
		b.WriteString(fmt.Sprintf("func (m %s) BpProcessor() bp.Processor {\n", en))
		b.WriteString(fmt.Sprintf("\treturn bp.NewEnumProcessor(bp.NewUint(%d))\n", nbits))
		b.WriteString("}\n\n")
	}

	for _, m := range proto.Messages {
		mn := toPascal(m.Name)
		b.WriteString(fmt.Sprintf("type %s struct {\n", mn))
		for _, f := range m.Fields {
			ts, err := idx.goType(f.Type)
			if err != nil {
				return "", err
			}
			b.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\"`\n", toPascal(f.Name), ts, f.Name))
		}
		b.WriteString("}\n\n")
	}

	for _, m := range proto.Messages {
		bits, err := idx.typeBits(TypeExpr{Name: m.Name})
		if err != nil {
			return "", err
		}
		bl := (bits + 7) / 8
		b.WriteString(fmt.Sprintf("const BYTES_LENGTH_%s uint32 = %d\n", strings.ToUpper(m.Name), bl))
	}
	if len(proto.Messages) > 0 {
		b.WriteString("\n")
	}

	for _, m := range proto.Messages {
		if err := idx.renderGoMessageMethods(&b, m); err != nil {
			return "", err
		}
	}

	return b.String(), nil
}

func (i *index) renderGoMessageMethods(b *strings.Builder, m Message) error {
	mn := toPascal(m.Name)
	up := strings.ToUpper(m.Name)
	bits, err := i.typeBits(TypeExpr{Name: m.Name})
	if err != nil {
		return err
	}
	fields := append([]MessageField{}, m.Fields...)
	sort.Slice(fields, func(a, c int) bool { return fields[a].Number < fields[c].Number })

	b.WriteString(fmt.Sprintf("func (m *%s) Size() uint32 { return BYTES_LENGTH_%s }\n\n", mn, up))
	b.WriteString(fmt.Sprintf("func (m *%s) String() string {\n", mn))
	b.WriteString("\tv, _ := jsonMarshal(m)\n")
	b.WriteString("\treturn string(v)\n")
	b.WriteString("}\n\n")

	for _, f := range fields {
		kind, resolved, ok, err := i.fixedFloatKindForType(f.Type)
		if err != nil {
			return err
		}
		if !ok {
			continue
		}
		suffix := fixedFloatKindSuffix(kind)
		name := toPascal(f.Name)
		target := "m." + name
		if resolved.ArraySize > 0 {
			elemCast := "int32"
			if a, ok := i.aliases[f.Type.Name]; ok && f.Type.ArraySize > 0 && a.Type.ArraySize == 0 {
				elemCast = toPascal(a.Name)
			}
			b.WriteString(fmt.Sprintf("func (m *%s) Set%s%sAt(i int, v float64) bool {\n", mn, name, suffix))
			b.WriteString(fmt.Sprintf("\tif i < 0 || i >= %d {\n", resolved.ArraySize))
			b.WriteString("\t\treturn false\n\t}\n")
			b.WriteString(fmt.Sprintf("\t%s[i] = %s(bp.BpFloatToInt32(v))\n", target, elemCast))
			b.WriteString("\treturn true\n")
			b.WriteString("}\n\n")
			b.WriteString(fmt.Sprintf("func (m *%s) Get%s%sAt(i int) (float64, bool) {\n", mn, name, suffix))
			b.WriteString(fmt.Sprintf("\tif i < 0 || i >= %d {\n", resolved.ArraySize))
			b.WriteString("\t\treturn 0, false\n\t}\n")
			b.WriteString(fmt.Sprintf("\treturn bp.BpInt32ToFloat(int32(%s[i])), true\n", target))
			b.WriteString("}\n\n")
		} else {
			castType, err := i.goCastTypeForField(f.Type, resolved)
			if err != nil {
				return err
			}
			b.WriteString(fmt.Sprintf("func (m *%s) Set%s%s(v float64) {\n", mn, name, suffix))
			b.WriteString(fmt.Sprintf("\t%s = %s(bp.BpFloatToInt32(v))\n", target, castType))
			b.WriteString("}\n\n")
			b.WriteString(fmt.Sprintf("func (m *%s) Get%s%s() float64 {\n", mn, name, suffix))
			b.WriteString(fmt.Sprintf("\treturn bp.BpInt32ToFloat(int32(%s))\n", target))
			b.WriteString("}\n\n")
		}
	}

	b.WriteString(fmt.Sprintf("func (m *%s) Encode() []byte {\n", mn))
	b.WriteString("\tctx := bp.NewEncodeContext(int(m.Size()))\n")
	b.WriteString("\tm.BpProcessor().Process(ctx, nil, m)\n")
	b.WriteString("\treturn ctx.Buffer()\n")
	b.WriteString("}\n\n")

	b.WriteString(fmt.Sprintf("func (m *%s) Decode(s []byte) {\n", mn))
	b.WriteString("\tctx := bp.NewDecodeContext(s)\n")
	b.WriteString("\tm.BpProcessor().Process(ctx, nil, m)\n")
	b.WriteString("}\n\n")

	b.WriteString(fmt.Sprintf("func (m *%s) BpProcessor() bp.Processor {\n", mn))
	b.WriteString("\tfieldDescriptors := []*bp.MessageFieldProcessor{\n")
	for _, f := range fields {
		expr, err := i.goProcessorExpr(f.Type)
		if err != nil {
			return err
		}
		b.WriteString(fmt.Sprintf("\t\tbp.NewMessageFieldProcessor(%d, %s),\n", f.Number, expr))
	}
	b.WriteString("\t}\n")
	b.WriteString(fmt.Sprintf("\treturn bp.NewMessageProcessor(false, %d, fieldDescriptors)\n", bits))
	b.WriteString("}\n\n")

	b.WriteString(fmt.Sprintf("func (m *%s) BpGetAccessor(di *bp.DataIndexer) bp.Accessor {\n", mn))
	b.WriteString("\tswitch di.F() {\n")
	for _, f := range fields {
		resolved, err := i.resolveAliasType(f.Type)
		if err != nil {
			return err
		}
		if _, ok := i.messages[resolved.Name]; !ok {
			continue
		}
		name := toPascal(f.Name)
		if resolved.ArraySize > 0 {
			b.WriteString(fmt.Sprintf("\tcase %d:\n\t\treturn &(m.%s[di.I(0)])\n", f.Number, name))
		} else {
			b.WriteString(fmt.Sprintf("\tcase %d:\n\t\treturn &(m.%s)\n", f.Number, name))
		}
	}
	b.WriteString("\tdefault:\n\t\treturn nil\n\t}\n")
	b.WriteString("}\n\n")

	b.WriteString(fmt.Sprintf("func (m *%s) BpSetByte(di *bp.DataIndexer, lshift int, bt byte) {\n", mn))
	b.WriteString("\tswitch di.F() {\n")
	for _, f := range fields {
		stmt, err := i.goSetByteStmt(f)
		if err != nil {
			return err
		}
		if stmt == "" {
			continue
		}
		b.WriteString(fmt.Sprintf("\tcase %d:\n\t\t%s\n", f.Number, stmt))
	}
	b.WriteString("\tdefault:\n\t\treturn\n\t}\n")
	b.WriteString("}\n\n")

	b.WriteString(fmt.Sprintf("func (m *%s) BpGetByte(di *bp.DataIndexer, rshift int) byte {\n", mn))
	b.WriteString("\tswitch di.F() {\n")
	for _, f := range fields {
		stmt, err := i.goGetByteStmt(f)
		if err != nil {
			return err
		}
		if stmt == "" {
			continue
		}
		b.WriteString(fmt.Sprintf("\tcase %d:\n\t\t%s\n", f.Number, stmt))
	}
	b.WriteString("\tdefault:\n\t\treturn byte(0)\n\t}\n")
	b.WriteString("}\n\n")

	b.WriteString(fmt.Sprintf("func (m *%s) BpProcessInt(di *bp.DataIndexer) {\n", mn))
	b.WriteString("\tswitch di.F() {\n")
	for _, f := range fields {
		stmt, err := i.goProcessIntStmt(f)
		if err != nil {
			return err
		}
		if stmt == "" {
			continue
		}
		b.WriteString(fmt.Sprintf("\tcase %d:\n\t\t%s\n", f.Number, stmt))
	}
	b.WriteString("\tdefault:\n\t\treturn\n\t}\n")
	b.WriteString("}\n\n")

	return nil
}

func (i *index) goProcessorExpr(t TypeExpr) (string, error) {
	if t.ArraySize > 0 {
		elemExpr, err := i.goProcessorExpr(TypeExpr{Name: t.Name})
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("bp.NewArray(false, %d, %s)", t.ArraySize, elemExpr), nil
	}
	s := t.Name
	switch s {
	case "bool":
		return "bp.NewBool()", nil
	case "byte":
		return "bp.NewByte()", nil
	}
	if m := reUint.FindStringSubmatch(s); len(m) == 2 {
		nbits, err := atoiBits(m[1])
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("bp.NewUint(%d)", nbits), nil
	}
	if m := reInt.FindStringSubmatch(s); len(m) == 2 {
		nbits, err := atoiBits(m[1])
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("bp.NewInt(%d)", nbits), nil
	}
	if isFixedFloatType(s) {
		return "bp.NewInt(32)", nil
	}
	if _, ok := i.enums[s]; ok {
		return fmt.Sprintf("(%s(0)).BpProcessor()", toPascal(s)), nil
	}
	if a, ok := i.aliases[s]; ok {
		an := toPascal(a.Name)
		if a.Type.ArraySize > 0 {
			return fmt.Sprintf("(%s{}).BpProcessor()", an), nil
		}
		return fmt.Sprintf("(%s(0)).BpProcessor()", an), nil
	}
	if _, ok := i.messages[s]; ok {
		return fmt.Sprintf("(&%s{}).BpProcessor()", toPascal(s)), nil
	}
	return "", fmt.Errorf("unsupported processor type %q", s)
}

func (i *index) resolveAliasType(t TypeExpr) (TypeExpr, error) {
	alias, ok := i.aliases[t.Name]
	if !ok {
		return t, nil
	}
	inner, err := i.resolveAliasType(alias.Type)
	if err != nil {
		return TypeExpr{}, err
	}
	if t.ArraySize > 0 {
		if inner.ArraySize > 0 {
			return TypeExpr{}, fmt.Errorf("nested arrays are not supported in native renderer")
		}
		inner.ArraySize = t.ArraySize
	}
	return inner, nil
}

func (i *index) goSetByteStmt(f MessageField) (string, error) {
	target, castType, resolved, err := i.goTargetCastAndResolved(f)
	if err != nil || target == "" {
		return "", err
	}
	if resolved.Name == "bool" {
		return fmt.Sprintf("%s = bp.Byte2bool(bt)", target), nil
	}
	return fmt.Sprintf("%s |= (%s(bt) << lshift)", target, castType), nil
}

func (i *index) goGetByteStmt(f MessageField) (string, error) {
	target, _, resolved, err := i.goTargetCastAndResolved(f)
	if err != nil || target == "" {
		return "", err
	}
	if resolved.Name == "bool" {
		return fmt.Sprintf("return bp.Bool2byte(%s) >> rshift", target), nil
	}
	return fmt.Sprintf("return byte(%s >> rshift)", target), nil
}

func (i *index) goProcessIntStmt(f MessageField) (string, error) {
	resolved, err := i.resolveAliasType(f.Type)
	if err != nil {
		return "", err
	}
	if _, ok := i.messages[resolved.Name]; ok {
		return "", nil
	}
	m := reInt.FindStringSubmatch(resolved.Name)
	if len(m) != 2 {
		return "", nil
	}
	nbits, err := atoiBits(m[1])
	if err != nil {
		return "", err
	}
	storage, err := storageBits(nbits)
	if err != nil {
		return "", err
	}
	shift := storage - nbits
	if shift <= 0 {
		return "", nil
	}
	target := "m." + toPascal(f.Name)
	if resolved.ArraySize > 0 {
		target += "[di.I(0)]"
	}
	return fmt.Sprintf("%s <<= %d; %s >>= %d", target, shift, target, shift), nil
}

func (i *index) goTargetCastAndResolved(f MessageField) (string, string, TypeExpr, error) {
	resolved, err := i.resolveAliasType(f.Type)
	if err != nil {
		return "", "", TypeExpr{}, err
	}
	if _, ok := i.messages[resolved.Name]; ok {
		return "", "", resolved, nil
	}
	target := "m." + toPascal(f.Name)
	if resolved.ArraySize > 0 {
		target += "[di.I(0)]"
	}
	castType, err := i.goCastTypeForField(f.Type, resolved)
	if err != nil {
		return "", "", TypeExpr{}, err
	}
	return target, castType, resolved, nil
}

func (i *index) goCastTypeForField(orig, resolved TypeExpr) (string, error) {
	if orig.ArraySize == 0 {
		if a, ok := i.aliases[orig.Name]; ok && a.Type.ArraySize == 0 {
			return toPascal(a.Name), nil
		}
	}
	if _, ok := i.enums[orig.Name]; ok && orig.ArraySize == 0 {
		return toPascal(orig.Name), nil
	}
	if _, ok := i.enums[resolved.Name]; ok {
		return toPascal(resolved.Name), nil
	}
	s := resolved.Name
	if isFixedFloatType(s) {
		return "int32", nil
	}
	switch s {
	case "bool":
		return "bool", nil
	case "byte":
		return "byte", nil
	}
	if m := reUint.FindStringSubmatch(s); len(m) == 2 {
		nbits, err := atoiBits(m[1])
		if err != nil {
			return "", err
		}
		storage, err := storageBits(nbits)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("uint%d", storage), nil
	}
	if m := reInt.FindStringSubmatch(s); len(m) == 2 {
		nbits, err := atoiBits(m[1])
		if err != nil {
			return "", err
		}
		storage, err := storageBits(nbits)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("int%d", storage), nil
	}
	return "", fmt.Errorf("unsupported go cast type for %q", orig.Name)
}

func (i *index) goType(t TypeExpr) (string, error) {
	s, err := i.goScalarType(TypeExpr{Name: t.Name})
	if err != nil {
		return "", err
	}
	if t.ArraySize > 0 {
		return fmt.Sprintf("[%d]%s", t.ArraySize, s), nil
	}
	return s, nil
}

func (i *index) goScalarType(t TypeExpr) (string, error) {
	s := t.Name
	if isFixedFloatType(s) {
		return "int32", nil
	}
	switch s {
	case "bool":
		return "bool", nil
	case "byte":
		return "byte", nil
	}
	if m := reUint.FindStringSubmatch(s); len(m) == 2 {
		nbits, err := atoiBits(m[1])
		if err != nil {
			return "", err
		}
		storage, err := storageBits(nbits)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("uint%d", storage), nil
	}
	if m := reInt.FindStringSubmatch(s); len(m) == 2 {
		nbits, err := atoiBits(m[1])
		if err != nil {
			return "", err
		}
		storage, err := storageBits(nbits)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("int%d", storage), nil
	}
	if _, ok := i.enums[s]; ok {
		return toPascal(s), nil
	}
	if _, ok := i.aliases[s]; ok {
		return toPascal(s), nil
	}
	if _, ok := i.messages[s]; ok {
		return toPascal(s), nil
	}
	return "", fmt.Errorf("unsupported go type %q", s)
}
