package native

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func RenderPy(proto *Proto, outDir string) (string, error) {
	if proto == nil {
		return "", fmt.Errorf("nil proto")
	}
	if outDir == "" {
		outDir = "."
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return "", err
	}
	path := filepath.Join(outDir, fmt.Sprintf("%s_bp.py", proto.Name))
	content, err := renderPyFile(proto)
	if err != nil {
		return "", err
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

func renderPyFile(proto *Proto) (string, error) {
	idx := newIndex(proto)
	var b strings.Builder

	b.WriteString("# Code generated by bitproto-go native renderer (experimental). DO NOT EDIT.\n\n")
	b.WriteString("import json\n")
	b.WriteString("import math\n")
	b.WriteString("from enum import IntEnum\n")
	b.WriteString("from bitprotolib import bp\n\n")
	b.WriteString("BP_FLOAT_SCALE = 100000000.0\n\n")
	b.WriteString("def bp_float_to_int32(v):\n")
	b.WriteString("    s = float(v) * BP_FLOAT_SCALE\n")
	b.WriteString("    if s > 2147483647:\n")
	b.WriteString("        return 2147483647\n")
	b.WriteString("    if s < -2147483648:\n")
	b.WriteString("        return -2147483648\n")
	b.WriteString("    return int(math.floor(s + 0.5)) if s >= 0 else int(math.ceil(s - 0.5))\n\n")
	b.WriteString("def bp_int32_to_float(v):\n")
	b.WriteString("    return float(v) / BP_FLOAT_SCALE\n\n")

	for _, a := range proto.Aliases {
		ts, err := idx.pyType(a.Type)
		if err != nil {
			return "", err
		}
		an := toPascal(a.Name)
		b.WriteString(fmt.Sprintf("%s = %s\n\n", an, ts))
		p, err := idx.pyProcessorExpr(a.Type)
		if err != nil {
			return "", err
		}
		b.WriteString(fmt.Sprintf("def bp_processor_%s():\n", an))
		b.WriteString(fmt.Sprintf("    return bp.AliasProcessor(%s)\n\n", p))
		defv, err := idx.pyDefault(a.Type)
		if err != nil {
			return "", err
		}
		b.WriteString(fmt.Sprintf("def bp_default_factory_%s():\n", an))
		b.WriteString(fmt.Sprintf("    return %s\n\n", defv))
	}

	for _, e := range proto.Enums {
		en := toPascal(e.Name)
		b.WriteString(fmt.Sprintf("class %s(IntEnum):\n", en))
		if len(e.Fields) == 0 {
			b.WriteString("    pass\n")
		} else {
			for _, f := range e.Fields {
				b.WriteString(fmt.Sprintf("    %s = %d\n", f.Name, f.Value))
			}
		}
		b.WriteString("\n")
		for _, f := range e.Fields {
			b.WriteString(fmt.Sprintf("%s = %s.%s\n", f.Name, en, f.Name))
		}
		b.WriteString("\n")
		nbits, err := idx.scalarBits(e.Base)
		if err != nil {
			return "", err
		}
		b.WriteString(fmt.Sprintf("def bp_processor_%s():\n", en))
		b.WriteString(fmt.Sprintf("    return bp.EnumProcessor(bp.Uint(%d))\n\n", nbits))
	}

	for _, m := range proto.Messages {
		bits, err := idx.typeBits(TypeExpr{Name: m.Name})
		if err != nil {
			return "", err
		}
		bl := (bits + 7) / 8
		b.WriteString(fmt.Sprintf("BYTES_LENGTH_%s = %d\n", strings.ToUpper(m.Name), bl))
	}
	b.WriteString("\n")

	for _, m := range proto.Messages {
		if err := idx.renderPyMessage(&b, m); err != nil {
			return "", err
		}
	}
	return b.String(), nil
}

func (i *index) renderPyMessage(b *strings.Builder, m Message) error {
	mn := toPascal(m.Name)
	up := strings.ToUpper(m.Name)
	bits, err := i.typeBits(TypeExpr{Name: m.Name})
	if err != nil {
		return err
	}
	fields := append([]MessageField{}, m.Fields...)
	sort.Slice(fields, func(a, c int) bool { return fields[a].Number < fields[c].Number })

	b.WriteString(fmt.Sprintf("class %s(bp.MessageBase):\n", mn))
	b.WriteString(fmt.Sprintf("    BYTES_LENGTH = BYTES_LENGTH_%s\n\n", up))
	b.WriteString("    def __init__(self):\n")
	if len(fields) == 0 {
		b.WriteString("        pass\n")
	} else {
		for _, f := range fields {
			defv, err := i.pyFieldDefault(f.Type)
			if err != nil {
				return err
			}
			b.WriteString(fmt.Sprintf("        self.%s = %s\n", f.Name, defv))
		}
	}
	b.WriteString("\n")

	for _, f := range fields {
		kind, resolved, ok, err := i.fixedFloatKindForType(f.Type)
		if err != nil {
			return err
		}
		if !ok {
			continue
		}
		suffix := kind
		if resolved.ArraySize > 0 {
			b.WriteString(fmt.Sprintf("    def set_%s_%s_at(self, i, v):\n", f.Name, suffix))
			b.WriteString(fmt.Sprintf("        if i < 0 or i >= %d:\n", resolved.ArraySize))
			b.WriteString("            return False\n")
			b.WriteString(fmt.Sprintf("        self.%s[i] = bp_float_to_int32(v)\n", f.Name))
			b.WriteString("        return True\n\n")
			b.WriteString(fmt.Sprintf("    def get_%s_%s_at(self, i):\n", f.Name, suffix))
			b.WriteString(fmt.Sprintf("        if i < 0 or i >= %d:\n", resolved.ArraySize))
			b.WriteString("            return 0.0, False\n")
			b.WriteString(fmt.Sprintf("        return bp_int32_to_float(self.%s[i]), True\n\n", f.Name))
		} else {
			b.WriteString(fmt.Sprintf("    def set_%s_%s(self, v):\n", f.Name, suffix))
			b.WriteString(fmt.Sprintf("        self.%s = bp_float_to_int32(v)\n", f.Name))
			b.WriteString("\n")
			b.WriteString(fmt.Sprintf("    def get_%s_%s(self):\n", f.Name, suffix))
			b.WriteString(fmt.Sprintf("        return bp_int32_to_float(self.%s)\n\n", f.Name))
		}
	}

	b.WriteString("    def bp_processor(self):\n")
	b.WriteString("        field_processors = [\n")
	for _, f := range fields {
		expr, err := i.pyProcessorExpr(f.Type)
		if err != nil {
			return err
		}
		b.WriteString(fmt.Sprintf("            bp.MessageFieldProcessor(%d, %s),\n", f.Number, expr))
	}
	b.WriteString("        ]\n")
	b.WriteString(fmt.Sprintf("        return bp.MessageProcessor(False, %d, field_processors)\n\n", bits))

	b.WriteString("    def bp_set_byte(self, di, lshift, bt):\n")
	if len(fields) == 0 {
		b.WriteString("        return\n\n")
	} else {
		for _, f := range fields {
			stmt, err := i.pySetByteStmt(f)
			if err != nil {
				return err
			}
			if stmt == "" {
				continue
			}
			b.WriteString(fmt.Sprintf("        if di.field_number == %d:\n", f.Number))
			b.WriteString(fmt.Sprintf("            %s\n", stmt))
		}
		b.WriteString("        return\n\n")
	}

	b.WriteString("    def bp_get_byte(self, di, rshift):\n")
	for _, f := range fields {
		stmt, err := i.pyGetByteStmt(f)
		if err != nil {
			return err
		}
		if stmt == "" {
			continue
		}
		b.WriteString(fmt.Sprintf("        if di.field_number == %d:\n", f.Number))
		b.WriteString(fmt.Sprintf("            %s\n", stmt))
	}
	b.WriteString("        return bp.byte(0)\n\n")

	b.WriteString("    def bp_get_accessor(self, di):\n")
	emitAny := false
	for _, f := range fields {
		resolved, err := i.resolveAliasType(f.Type)
		if err != nil {
			return err
		}
		if _, ok := i.messages[resolved.Name]; !ok {
			continue
		}
		emitAny = true
		if resolved.ArraySize > 0 {
			b.WriteString(fmt.Sprintf("        if di.field_number == %d:\n", f.Number))
			b.WriteString(fmt.Sprintf("            return self.%s[di.i(0)]\n", f.Name))
		} else {
			b.WriteString(fmt.Sprintf("        if di.field_number == %d:\n", f.Number))
			b.WriteString(fmt.Sprintf("            return self.%s\n", f.Name))
		}
	}
	if !emitAny {
		b.WriteString("        return bp.NilAccessor()\n\n")
	} else {
		b.WriteString("        return bp.NilAccessor()\n\n")
	}

	b.WriteString("    def encode(self):\n")
	b.WriteString("        s = bytearray(self.BYTES_LENGTH)\n")
	b.WriteString("        ctx = bp.ProcessContext(True, s)\n")
	b.WriteString("        self.bp_processor().process(ctx, bp.NIL_DATA_INDEXER, self)\n")
	b.WriteString("        return ctx.s\n\n")

	b.WriteString("    def decode(self, s):\n")
	b.WriteString("        assert len(s) >= self.BYTES_LENGTH, bp.NotEnoughBytes()\n")
	b.WriteString("        ctx = bp.ProcessContext(False, s)\n")
	b.WriteString("        self.bp_processor().process(ctx, bp.NIL_DATA_INDEXER, self)\n\n")

	b.WriteString("    def bp_process_int(self, di):\n")
	hasIntFix := false
	for _, f := range fields {
		stmt, err := i.pyProcessIntStmt(f)
		if err != nil {
			return err
		}
		if stmt == "" {
			continue
		}
		hasIntFix = true
		b.WriteString(fmt.Sprintf("        if di.field_number == %d:\n", f.Number))
		b.WriteString(fmt.Sprintf("            %s\n", stmt))
		b.WriteString("            return\n")
	}
	if !hasIntFix {
		b.WriteString("        return\n\n")
	} else {
		b.WriteString("        return\n\n")
	}

	b.WriteString("\n")
	return nil
}

func (i *index) pyProcessorExpr(t TypeExpr) (string, error) {
	if t.ArraySize > 0 {
		elem, err := i.pyProcessorExpr(TypeExpr{Name: t.Name})
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("bp.Array(False, %d, %s)", t.ArraySize, elem), nil
	}
	s := t.Name
	switch s {
	case "bool":
		return "bp.Bool()", nil
	case "byte":
		return "bp.Byte()", nil
	}
	if m := reUint.FindStringSubmatch(s); len(m) == 2 {
		nbits, err := atoiBits(m[1])
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("bp.Uint(%d)", nbits), nil
	}
	if m := reInt.FindStringSubmatch(s); len(m) == 2 {
		nbits, err := atoiBits(m[1])
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("bp.Int(%d)", nbits), nil
	}
	if isFixedFloatType(s) {
		return "bp.Int(32)", nil
	}
	if _, ok := i.enums[s]; ok {
		return fmt.Sprintf("bp_processor_%s()", toPascal(s)), nil
	}
	if _, ok := i.aliases[s]; ok {
		return fmt.Sprintf("bp_processor_%s()", toPascal(s)), nil
	}
	if _, ok := i.messages[s]; ok {
		return fmt.Sprintf("%s().bp_processor()", toPascal(s)), nil
	}
	return "", fmt.Errorf("unsupported py processor type %q", s)
}

func (i *index) pyFieldDefault(t TypeExpr) (string, error) {
	if t.ArraySize > 0 {
		elemDef, err := i.pyScalarDefault(TypeExpr{Name: t.Name})
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("[%s for _ in range(%d)]", elemDef, t.ArraySize), nil
	}
	if _, ok := i.aliases[t.Name]; ok {
		return fmt.Sprintf("bp_default_factory_%s()", toPascal(t.Name)), nil
	}
	return i.pyScalarDefault(t)
}

func (i *index) pyType(t TypeExpr) (string, error) {
	if t.ArraySize > 0 {
		return "list", nil
	}
	return i.pyScalarType(t)
}

func (i *index) pyScalarType(t TypeExpr) (string, error) {
	s := t.Name
	if s == "bool" {
		return "bool", nil
	}
	if isFixedFloatType(s) {
		return "int", nil
	}
	if s == "byte" || reUint.MatchString(s) || reInt.MatchString(s) {
		return "int", nil
	}
	if _, ok := i.enums[s]; ok {
		return toPascal(s), nil
	}
	if _, ok := i.aliases[s]; ok {
		return toPascal(s), nil
	}
	if _, ok := i.messages[s]; ok {
		return toPascal(s), nil
	}
	return "", fmt.Errorf("unsupported py type %q", s)
}

func (i *index) pyDefault(t TypeExpr) (string, error) {
	return i.pyFieldDefault(t)
}

func (i *index) pyScalarDefault(t TypeExpr) (string, error) {
	s := t.Name
	if s == "bool" {
		return "False", nil
	}
	if isFixedFloatType(s) {
		return "0", nil
	}
	if s == "byte" || reUint.MatchString(s) || reInt.MatchString(s) {
		return "0", nil
	}
	if e, ok := i.enums[s]; ok {
		if len(e.Fields) == 0 {
			return "0", nil
		}
		return fmt.Sprintf("%s.%s", toPascal(s), e.Fields[0].Name), nil
	}
	if _, ok := i.messages[s]; ok {
		return fmt.Sprintf("%s()", toPascal(s)), nil
	}
	if _, ok := i.aliases[s]; ok {
		return fmt.Sprintf("bp_default_factory_%s()", toPascal(s)), nil
	}
	return "0", nil
}

func (i *index) pySetByteStmt(f MessageField) (string, error) {
	target, resolved, err := i.pyTargetAndResolved(f)
	if err != nil || target == "" {
		return "", err
	}
	if resolved.Name == "bool" {
		return fmt.Sprintf("%s = bool(bt)", target), nil
	}
	if m := reInt.FindStringSubmatch(resolved.Name); len(m) == 2 {
		nbits, err := atoiBits(m[1])
		if err != nil {
			return "", err
		}
		storage, err := storageBits(nbits)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("%s |= bp.int%d((int(bt) << lshift))", target, storage), nil
	}
	if isFixedFloatType(resolved.Name) {
		return fmt.Sprintf("%s |= bp.int32((int(bt) << lshift))", target), nil
	}
	return fmt.Sprintf("%s |= (int(bt) << lshift)", target), nil
}

func (i *index) pyGetByteStmt(f MessageField) (string, error) {
	target, _, err := i.pyTargetAndResolved(f)
	if err != nil || target == "" {
		return "", err
	}
	return fmt.Sprintf("return (%s >> rshift) & 255", target), nil
}

func (i *index) pyProcessIntStmt(f MessageField) (string, error) {
	_, resolved, err := i.pyTargetAndResolved(f)
	if err != nil {
		return "", err
	}
	m := reInt.FindStringSubmatch(resolved.Name)
	if len(m) != 2 {
		if isFixedFloatType(resolved.Name) {
			target := "self." + f.Name
			if resolved.ArraySize > 0 {
				target += "[di.i(0)]"
			}
			return fmt.Sprintf("if (%s >> 31) & 1: %s |= -(1 << 32)", target, target), nil
		}
		return "", nil
	}
	nbits, err := atoiBits(m[1])
	if err != nil {
		return "", err
	}
	target := "self." + f.Name
	if resolved.ArraySize > 0 {
		target += "[di.i(0)]"
	}
	return fmt.Sprintf("if (%s >> %d) & 1: %s |= -(1 << %d)", target, nbits-1, target, nbits), nil
}

func (i *index) pyTargetAndResolved(f MessageField) (string, TypeExpr, error) {
	resolved, err := i.resolveAliasType(f.Type)
	if err != nil {
		return "", TypeExpr{}, err
	}
	if _, ok := i.messages[resolved.Name]; ok {
		return "", resolved, nil
	}
	target := "self." + f.Name
	if resolved.ArraySize > 0 {
		target += "[di.i(0)]"
	}
	return target, resolved, nil
}
