package native

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var (
	reUint = regexp.MustCompile(`^uint(\d+)$`)
	reInt  = regexp.MustCompile(`^int(\d+)$`)
)

func RenderC(proto *Proto, outDir string) (string, string, error) {
	if proto == nil {
		return "", "", fmt.Errorf("nil proto")
	}
	if outDir == "" {
		outDir = "."
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return "", "", err
	}

	hPath := filepath.Join(outDir, fmt.Sprintf("%s_bp.h", proto.Name))
	cPath := filepath.Join(outDir, fmt.Sprintf("%s_bp.c", proto.Name))

	hContent, err := renderHeader(proto)
	if err != nil {
		return "", "", err
	}
	cContent, err := renderSource(proto)
	if err != nil {
		return "", "", err
	}

	if err := os.WriteFile(hPath, []byte(hContent), 0o644); err != nil {
		return "", "", err
	}
	if err := os.WriteFile(cPath, []byte(cContent), 0o644); err != nil {
		return "", "", err
	}
	return hPath, cPath, nil
}

func renderHeader(proto *Proto) (string, error) {
	idx := newIndex(proto)
	var b strings.Builder
	guard := strings.ToUpper(proto.Name)
	guard = strings.ReplaceAll(guard, "-", "_")
	guard = strings.ReplaceAll(guard, ".", "_")
	guard = "__BITPROTO_NATIVE_" + guard + "_H__"

	b.WriteString("// Code generated by bitproto-go native renderer (experimental). DO NOT EDIT.\n")
	b.WriteString("#ifndef " + guard + "\n")
	b.WriteString("#define " + guard + " 1\n\n")
	b.WriteString("#include <inttypes.h>\n")
	b.WriteString("#include <stddef.h>\n")
	b.WriteString("#include <stdint.h>\n")
	b.WriteString("#include <limits.h>\n")
	b.WriteString("#ifndef __cplusplus\n")
	b.WriteString("#include <stdbool.h>\n")
	b.WriteString("#endif\n\n")
	b.WriteString("#include \"bitproto.h\"\n\n")

	for _, c := range proto.Consts {
		b.WriteString(fmt.Sprintf("#define %s %s\n", c.Name, c.Value))
	}
	if len(proto.Consts) > 0 {
		b.WriteString("\n")
	}

	for _, a := range proto.Aliases {
		ts, err := idx.cTypeDecl(a.Type, a.Name)
		if err != nil {
			return "", err
		}
		b.WriteString("typedef " + ts + ";\n")
	}
	if len(proto.Aliases) > 0 {
		b.WriteString("\n")
	}

	for _, e := range proto.Enums {
		base, err := idx.cScalarType(TypeExpr{Name: e.Base})
		if err != nil {
			return "", fmt.Errorf("enum %s: %w", e.Name, err)
		}
		b.WriteString(fmt.Sprintf("typedef %s %s;\n", base, e.Name))
		for _, f := range e.Fields {
			b.WriteString(fmt.Sprintf("#define %s %d\n", f.Name, f.Value))
		}
		b.WriteString("\n")
	}

	for _, m := range proto.Messages {
		b.WriteString(fmt.Sprintf("struct %s {\n", m.Name))
		for _, f := range m.Fields {
			ts, err := idx.cTypeDecl(f.Type, f.Name)
			if err != nil {
				return "", fmt.Errorf("message %s field %s: %w", m.Name, f.Name, err)
			}
			b.WriteString("    " + ts + ";\n")
		}
		b.WriteString("};\n\n")
	}

	for _, m := range proto.Messages {
		bits, err := idx.typeBits(TypeExpr{Name: m.Name})
		if err != nil {
			return "", err
		}
		bl := (bits + 7) / 8
		name := strings.ToUpper(m.Name)
		b.WriteString(fmt.Sprintf("#define BYTES_LENGTH_%s %d\n", name, bl))
	}
	if len(proto.Messages) > 0 {
		b.WriteString("\n")
	}

	for _, m := range proto.Messages {
		b.WriteString(fmt.Sprintf("size_t Encode%s(struct %s *m, unsigned char *s);\n", m.Name, m.Name))
		b.WriteString(fmt.Sprintf("size_t Decode%s(struct %s *m, unsigned char *s);\n", m.Name, m.Name))
		b.WriteString(fmt.Sprintf("int Json%s(struct %s *m, char *s);\n", m.Name, m.Name))
	}

	b.WriteString("\n")
	for _, m := range proto.Messages {
		for _, f := range m.Fields {
			kind, resolved, ok, err := idx.fixedFloatKindForType(f.Type)
			if err != nil {
				return "", err
			}
			if !ok {
				continue
			}
			suffix := fixedFloatKindSuffix(kind)
			fn := toPascal(f.Name)
			if resolved.ArraySize > 0 {
				b.WriteString(fmt.Sprintf("static inline void Set%s%s%sAt(struct %s *m, size_t i, double v) { if (i < %d) { m->%s[i] = BpFloatToInt32(v); } }\n", m.Name, fn, suffix, m.Name, resolved.ArraySize, f.Name))
				b.WriteString(fmt.Sprintf("static inline double Get%s%s%sAt(const struct %s *m, size_t i) { if (i < %d) { return BpInt32ToFloat(m->%s[i]); } return 0.0; }\n", m.Name, fn, suffix, m.Name, resolved.ArraySize, f.Name))
			} else {
				b.WriteString(fmt.Sprintf("static inline void Set%s%s%s(struct %s *m, double v) { m->%s = BpFloatToInt32(v); }\n", m.Name, fn, suffix, m.Name, f.Name))
				b.WriteString(fmt.Sprintf("static inline double Get%s%s%s(const struct %s *m) { return BpInt32ToFloat(m->%s); }\n", m.Name, fn, suffix, m.Name, f.Name))
			}
		}
	}

	b.WriteString("\n#endif\n")
	return b.String(), nil
}

func renderSource(proto *Proto) (string, error) {
	idx := newIndex(proto)
	var b strings.Builder
	b.WriteString("// Code generated by bitproto-go native renderer (experimental). DO NOT EDIT.\n")
	b.WriteString("#include \"bitproto.h\"\n")
	b.WriteString(fmt.Sprintf("#include \"%s_bp.h\"\n\n", proto.Name))

	arrayJobs := collectArrayJobs(proto)

	for _, job := range arrayJobs {
		b.WriteString(fmt.Sprintf("void %s(void *data, struct BpProcessorContext *ctx);\n", job.FuncName))
	}
	for _, a := range proto.Aliases {
		b.WriteString(fmt.Sprintf("void %s(void *data, struct BpProcessorContext *ctx);\n", aliasProcName(a.Name)))
	}
	for _, m := range proto.Messages {
		b.WriteString(fmt.Sprintf("void %s(void *data, struct BpProcessorContext *ctx);\n", msgProcName(m.Name)))
	}
	b.WriteString("\n")

	for _, job := range arrayJobs {
		elemExpr, err := idx.bpTypeExpr(job.ElemType, bpContext{Kind: "array_elem"})
		if err != nil {
			return "", err
		}
		b.WriteString(fmt.Sprintf("void %s(void *data, struct BpProcessorContext *ctx) {\n", job.FuncName))
		b.WriteString(fmt.Sprintf("    struct BpArrayDescriptor descriptor = BpArrayDescriptor(false, %d, %s);\n", job.Cap, elemExpr))
		b.WriteString("    BpEndecodeArray(&descriptor, ctx, data);\n")
		b.WriteString("}\n\n")
	}

	for _, a := range proto.Aliases {
		toExpr, err := idx.bpAliasTargetExpr(a)
		if err != nil {
			return "", err
		}
		b.WriteString(fmt.Sprintf("void %s(void *data, struct BpProcessorContext *ctx) {\n", aliasProcName(a.Name)))
		b.WriteString(fmt.Sprintf("    struct BpAliasDescriptor descriptor = BpAliasDescriptor(%s);\n", toExpr))
		b.WriteString("    BpEndecodeAlias(&descriptor, ctx, data);\n")
		b.WriteString("}\n\n")
	}

	for _, m := range proto.Messages {
		fields := append([]MessageField{}, m.Fields...)
		sort.Slice(fields, func(i, j int) bool { return fields[i].Number < fields[j].Number })

		b.WriteString(fmt.Sprintf("void BpFieldDescriptorsInit%s(struct %s *m, struct BpMessageFieldDescriptor *fds) {\n", m.Name, m.Name))
		for iField, f := range fields {
			tExpr, err := idx.bpTypeExpr(f.Type, bpContext{Kind: "field", MsgName: m.Name, FieldNum: f.Number})
			if err != nil {
				return "", err
			}
			b.WriteString(fmt.Sprintf("    fds[%d] = BpMessageFieldDescriptor((void *)&(m->%s), %s, \"%s\");\n", iField, f.Name, tExpr, f.Name))
		}
		b.WriteString("}\n\n")

		nbits, err := idx.typeBits(TypeExpr{Name: m.Name})
		if err != nil {
			return "", err
		}

		b.WriteString(fmt.Sprintf("void %s(void *data, struct BpProcessorContext *ctx) {\n", msgProcName(m.Name)))
		b.WriteString(fmt.Sprintf("    struct %s *m = (struct %s *)(data);\n", m.Name, m.Name))
		b.WriteString(fmt.Sprintf("    struct BpMessageFieldDescriptor field_descriptors[%d];\n", len(fields)))
		b.WriteString(fmt.Sprintf("    BpFieldDescriptorsInit%s(m, field_descriptors);\n", m.Name))
		b.WriteString(fmt.Sprintf("    struct BpMessageDescriptor descriptor = BpMessageDescriptor(false, %d, %d, field_descriptors);\n", len(fields), nbits))
		b.WriteString("    BpEndecodeMessage(&descriptor, ctx, data);\n")
		b.WriteString("}\n\n")
	}

	for _, m := range proto.Messages {
		up := strings.ToUpper(m.Name)
		b.WriteString(fmt.Sprintf("size_t Encode%s(struct %s *m, unsigned char *s) {\n", m.Name, m.Name))
		b.WriteString("    struct BpProcessorContext ctx = BpProcessorContext(true, s);\n")
		b.WriteString(fmt.Sprintf("    %s((void *)m, &ctx);\n", msgProcName(m.Name)))
		b.WriteString(fmt.Sprintf("    return BYTES_LENGTH_%s;\n", up))
		b.WriteString("}\n\n")
		b.WriteString(fmt.Sprintf("size_t Decode%s(struct %s *m, unsigned char *s) {\n", m.Name, m.Name))
		b.WriteString("    struct BpProcessorContext ctx = BpProcessorContext(false, s);\n")
		b.WriteString(fmt.Sprintf("    %s((void *)m, &ctx);\n", msgProcName(m.Name)))
		b.WriteString(fmt.Sprintf("    return BYTES_LENGTH_%s;\n", up))
		b.WriteString("}\n\n")
		b.WriteString(fmt.Sprintf("int Json%s(struct %s *m, char *s) {\n", m.Name, m.Name))
		b.WriteString("    (void)m;\n")
		b.WriteString("    if (s) { s[0] = '{'; s[1] = '}'; s[2] = '\\0'; }\n")
		b.WriteString("    return 2;\n")
		b.WriteString("}\n\n")
	}
	return b.String(), nil
}

type bpContext struct {
	Kind     string
	Alias    string
	MsgName  string
	FieldNum int
}

type arrayJob struct {
	FuncName string
	ElemType TypeExpr
	Cap      int
}

func collectArrayJobs(proto *Proto) []arrayJob {
	jobs := []arrayJob{}
	for _, a := range proto.Aliases {
		if a.Type.ArraySize > 0 {
			jobs = append(jobs, arrayJob{
				FuncName: arrayProcNameForAlias(a.Name),
				ElemType: TypeExpr{Name: a.Type.Name},
				Cap:      a.Type.ArraySize,
			})
		}
	}
	for _, m := range proto.Messages {
		for _, f := range m.Fields {
			if f.Type.ArraySize > 0 {
				jobs = append(jobs, arrayJob{
					FuncName: arrayProcNameForField(m.Name, f.Number),
					ElemType: TypeExpr{Name: f.Type.Name},
					Cap:      f.Type.ArraySize,
				})
			}
		}
	}
	return jobs
}

func aliasProcName(name string) string {
	return "BpNativeProcess" + toPascal(name)
}

func msgProcName(name string) string {
	return "BpNativeProcess" + toPascal(name)
}

func arrayProcNameForAlias(name string) string {
	return "BpNativeProcessArray" + toPascal(name)
}

func arrayProcNameForField(msg string, fieldNum int) string {
	return fmt.Sprintf("BpNativeProcessArray%s%d", toPascal(msg), fieldNum)
}

func (i *index) bpAliasTargetExpr(a Alias) (string, error) {
	if a.Type.ArraySize > 0 {
		nbits, err := i.typeBits(a.Type)
		if err != nil {
			return "", err
		}
		elemC, err := i.cScalarType(TypeExpr{Name: a.Type.Name})
		if err != nil {
			return "", err
		}
		sizeExpr := fmt.Sprintf("%d * sizeof(%s)", a.Type.ArraySize, elemC)
		return fmt.Sprintf("BpArray(%d, %s, %s, NULL)", nbits, sizeExpr, arrayProcNameForAlias(a.Name)), nil
	}
	return i.bpTypeExpr(a.Type, bpContext{Kind: "alias_target"})
}

func (i *index) bpTypeExpr(t TypeExpr, ctx bpContext) (string, error) {
	if t.ArraySize > 0 {
		nbits, err := i.typeBits(t)
		if err != nil {
			return "", err
		}
		elemC, err := i.cScalarType(TypeExpr{Name: t.Name})
		if err != nil {
			return "", err
		}
		sizeExpr := fmt.Sprintf("%d * sizeof(%s)", t.ArraySize, elemC)
		procName := ""
		switch ctx.Kind {
		case "alias":
			procName = arrayProcNameForAlias(ctx.Alias)
		case "field":
			procName = arrayProcNameForField(ctx.MsgName, ctx.FieldNum)
		default:
			return "", fmt.Errorf("array bp type requires alias/field context")
		}
		return fmt.Sprintf("BpArray(%d, %s, %s, NULL)", nbits, sizeExpr, procName), nil
	}

	name := t.Name
	if name == "bool" {
		return "BpBool()", nil
	}
	if name == "byte" {
		return "BpByte()", nil
	}
	if m := reUint.FindStringSubmatch(name); len(m) == 2 {
		nbits, err := atoiBits(m[1])
		if err != nil {
			return "", err
		}
		ct, err := i.cScalarType(TypeExpr{Name: name})
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("BpUint(%d, sizeof(%s))", nbits, ct), nil
	}
	if m := reInt.FindStringSubmatch(name); len(m) == 2 {
		nbits, err := atoiBits(m[1])
		if err != nil {
			return "", err
		}
		ct, err := i.cScalarType(TypeExpr{Name: name})
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("BpInt(%d, sizeof(%s))", nbits, ct), nil
	}
	if isFixedFloatType(name) {
		ct, err := i.cScalarType(TypeExpr{Name: name})
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("BpInt(32, sizeof(%s))", ct), nil
	}
	if e, ok := i.enums[name]; ok {
		nbits, err := i.scalarBits(e.Base)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("BpEnum(%d, sizeof(%s))", nbits, name), nil
	}
	if a, ok := i.aliases[name]; ok {
		nbits, err := i.typeBits(a.Type)
		if err != nil {
			return "", err
		}
		toFlag, err := i.typeFlag(a.Type)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("BpAlias(%d, sizeof(%s), %s, NULL, %s)", nbits, name, aliasProcName(name), toFlag), nil
	}
	if _, ok := i.messages[name]; ok {
		nbits, err := i.typeBits(TypeExpr{Name: name})
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("BpMessage(%d, sizeof(struct %s), %s, NULL)", nbits, name, msgProcName(name)), nil
	}
	return "", fmt.Errorf("unsupported bp type %q", name)
}

func (i *index) typeFlag(t TypeExpr) (string, error) {
	if t.ArraySize > 0 {
		return "BP_TYPE_ARRAY", nil
	}
	name := t.Name
	if name == "bool" {
		return "BP_TYPE_BOOL", nil
	}
	if name == "byte" {
		return "BP_TYPE_BYTE", nil
	}
	if reUint.MatchString(name) {
		return "BP_TYPE_UINT", nil
	}
	if reInt.MatchString(name) {
		return "BP_TYPE_INT", nil
	}
	if isFixedFloatType(name) {
		return "BP_TYPE_INT", nil
	}
	if _, ok := i.enums[name]; ok {
		return "BP_TYPE_ENUM", nil
	}
	if _, ok := i.aliases[name]; ok {
		return "BP_TYPE_ALIAS", nil
	}
	if _, ok := i.messages[name]; ok {
		return "BP_TYPE_MESSAGE", nil
	}
	return "", fmt.Errorf("unsupported type flag for %q", name)
}

type index struct {
	aliases  map[string]Alias
	enums    map[string]Enum
	messages map[string]Message
}

func newIndex(p *Proto) *index {
	i := &index{
		aliases:  map[string]Alias{},
		enums:    map[string]Enum{},
		messages: map[string]Message{},
	}
	for _, a := range p.Aliases {
		i.aliases[a.Name] = a
	}
	for _, e := range p.Enums {
		i.enums[e.Name] = e
	}
	for _, m := range p.Messages {
		i.messages[m.Name] = m
	}
	return i
}

func (i *index) cTypeDecl(t TypeExpr, name string) (string, error) {
	base, err := i.cScalarType(TypeExpr{Name: t.Name})
	if err != nil {
		return "", err
	}
	if t.ArraySize > 0 {
		return fmt.Sprintf("%s %s[%d]", base, name, t.ArraySize), nil
	}
	if name != "" {
		return fmt.Sprintf("%s %s", base, name), nil
	}
	return base, nil
}

func (i *index) cScalarType(t TypeExpr) (string, error) {
	s := t.Name
	switch s {
	case "bool":
		return "bool", nil
	case "byte":
		return "unsigned char", nil
	}
	if m := reUint.FindStringSubmatch(s); len(m) == 2 {
		nbits, err := atoiBits(m[1])
		if err != nil {
			return "", err
		}
		storage, err := storageBits(nbits)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("uint%d_t", storage), nil
	}
	if m := reInt.FindStringSubmatch(s); len(m) == 2 {
		nbits, err := atoiBits(m[1])
		if err != nil {
			return "", err
		}
		storage, err := storageBits(nbits)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("int%d_t", storage), nil
	}
	if isFixedFloatType(s) {
		return "int32_t", nil
	}
	if _, ok := i.enums[s]; ok {
		return s, nil
	}
	if _, ok := i.aliases[s]; ok {
		return s, nil
	}
	if _, ok := i.messages[s]; ok {
		return "struct " + s, nil
	}
	return "", fmt.Errorf("unsupported type %q", s)
}

func (i *index) typeBits(t TypeExpr) (int, error) {
	scalarBits, err := i.scalarBits(t.Name)
	if err != nil {
		return 0, err
	}
	if t.ArraySize > 0 {
		return scalarBits * t.ArraySize, nil
	}
	return scalarBits, nil
}

func (i *index) scalarBits(name string) (int, error) {
	switch name {
	case "bool":
		return 1, nil
	case "byte":
		return 8, nil
	}
	if m := reUint.FindStringSubmatch(name); len(m) == 2 {
		return atoiBits(m[1])
	}
	if m := reInt.FindStringSubmatch(name); len(m) == 2 {
		return atoiBits(m[1])
	}
	if isFixedFloatType(name) {
		return 32, nil
	}
	if e, ok := i.enums[name]; ok {
		return i.scalarBits(e.Base)
	}
	if a, ok := i.aliases[name]; ok {
		return i.typeBits(a.Type)
	}
	if m, ok := i.messages[name]; ok {
		total := 0
		fields := append([]MessageField{}, m.Fields...)
		sort.Slice(fields, func(x, y int) bool { return fields[x].Number < fields[y].Number })
		for _, f := range fields {
			bits, err := i.typeBits(f.Type)
			if err != nil {
				return 0, err
			}
			total += bits
		}
		return total, nil
	}
	return 0, fmt.Errorf("cannot resolve bits for type %q", name)
}

func atoiBits(s string) (int, error) {
	v := 0
	for _, ch := range s {
		if ch < '0' || ch > '9' {
			return 0, fmt.Errorf("invalid bit width %q", s)
		}
		v = v*10 + int(ch-'0')
	}
	if v <= 0 {
		return 0, fmt.Errorf("invalid bit width %q", s)
	}
	return v, nil
}

func storageBits(n int) (int, error) {
	switch {
	case n <= 8:
		return 8, nil
	case n <= 16:
		return 16, nil
	case n <= 32:
		return 32, nil
	case n <= 64:
		return 64, nil
	default:
		return 0, fmt.Errorf("bit width %d exceeds 64", n)
	}
}
